"use client"
import ClientProvider from "@/components/ClientProvider";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import localFont from "next/font/local";
import "./globals.css";
import AblyClientProvider from "@/components/AblyProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/* export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

// TODO: Make the session provider a separate client component

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AblyClientProvider>
          <AppRouterCacheProvider>
            <ClientProvider>{children}</ClientProvider>
          </AppRouterCacheProvider>
        </AblyClientProvider>
      </body>
    </html>
  );
}
